version: '3'

services:
  mariadb:
    image: mariadb:lts-jammy
    container_name: mariadb_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
    networks:
      - databasenetwork

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2.1
    container_name: phpmyadmin_container
    restart: always
    environment:
      PMA_HOST: mariadb
    ports:
      - "8080:80"
    networks:
      - databasenetwork

networks:
  databasenetwork:
    driver: bridge
